### ISSUE TITLE
RuntimeError: The 'data' object was created by an older version of PyG. If this error occurred while loading an already existing dataset, remove the 'processed/' directory in the dataset's root folder and try again.

### ISSUE THREAD

**Issue by Krystal9917** [friendllcc/DMalNet#3]
Hi @friendllcc , thank you for the work, but I met a problem.
When I want to load the dataset as you mentioned in the README.md, there occurs an error.

`Traceback (most recent call last):`
  `File "/home/user/projects/dmalnet/test.py", line 6, in <module>`
    `print(graph.x)`
  `File "/home/user/miniconda3/lib/python3.8/site-packages/torch_geometric/data/data.py", line 752, in x`
    `return self['x'] if 'x' in self._store else None`
  `File "/home/user/miniconda3/lib/python3.8/site-packages/torch_geometric/data/data.py", line 423, in __getattr__`
    `raise RuntimeError(
RuntimeError: The 'data' object was created by an older version of PyG. If this error occurred while loading an already existing dataset, remove the 'processed/' directory in the dataset's root folder and try again.`

My Code is as follows:

`dataset = torch.load("./data/demo_classification_test.pt")`
`graph = dataset[0]`
`print(graph.x)`
`print(graph.y)`
`print(graph.edge_index)`
`print(graph.edge_attr)`

My environment is as follows:

torch                  1.11.0+cu113
torch-cluster          1.6.0
torch-geometric        2.2.0
torch-scatter          2.0.9
torch-sparse           0.6.14
torch-spline-conv      1.2.1

I think the demo dataset demo_classification_test.pt exists some problems maybe. So could you please share a new demo data or the entire data with us? Sincerely hope your reply!

**Comment by friendllcc** [comment]
This problem is caused by the different torch-geometric version.
My torch-geometric version is 1.7.0
